import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} text-base-content`}>
				<Sidebar />
				<div className='w-[80%] ml-auto'>
					<main className='flex w-full  h-full '>
						<div className='p-4 w-full h-full'>{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
